stages:
  generate_data:
    cmd: python generate_data.py data_/
    deps:
    - generate_data.py
    params:
    - generate_data
    - geometry
    - simulate
    outs:
      - data_/LNet/
          # persist: true
      - data_/p0/
          # persist: true
      - data_/sensors/
          # persist: true
      - data_/p_data/
          # persist: true
    # always_changed: true

  # simulate:
  #   cmd: python simulate.py data/LNet/ data/
  #   deps:
  #   - data/LNet/
  #   - simulate.py
  #   - simulator.py
  #   outs:
  #   params:
  #     - geometry

  reconstruct:
    cmd: python reconstruct.py data_/
    deps:
    - reconstruct.py
    outs:
    - data_/p_r/
        # persist: true
    params: 
      - geometry
      - simulate

  # add_noise:
  #   cmd: python add_noise.py
  #   deps:
  #     - simulated_data/
  #   outs:
  #     - noisy_data/

  # train_network:
  #   cmd: python train_network.py
  #   deps:
  #     - noisy_data/
  #   outs:
  #     - model/
  #   metrics_no_cache:
  #     - metrics/training_metrics.json

  # test_network:
  #   cmd: python test_network.py
  #   deps:
  #     - model/
  #     - noisy_data/
  #   outs:
  #     - test_results/
  #   metrics_no_cache:
  #     - metrics/test_metrics.json
