stages:
  generate_data:
    cmd: python generate_data.py data_/
    deps:
    - generate_data.py
    params:
    - generate_data
    - geometry
    # - simulate
    outs:
      - data_/LNet/
          # persist: true
      - data_/p0/
          # persist: true
      - data_/sensors/
          # persist: true
      - data_/p_data/
          # persist: true
      - data_/c/
          # persist: true
    # always_changed: true

  reconstruct:
    cmd: python reconstruct.py data_/
    deps:
    - reconstruct.py
    - time_reversal.py
    - data_/p_data/
    - data_/sensors/
    - data_/p0/
    outs:
    - data_/p_r/
        # persist: true
    params: 
      - geometry
      # - simulate
    # always_changed: true

  visualize:
    cmd: python vis.py
    deps:
    - vis.py
    - data_/p0/
    # - data_/p_r/
    # - data_/p_data/
    # - data_/sensors/
    # params:
    # - geometry
    # - reconstruct
    # - simulate
    # outs:
    # - data_/visualizations/
        # persist: true



  # add_noise:
  #   cmd: python add_noise.py
  #   deps:
  #     - simulated_data/
  #   outs:
  #     - noisy_data/

  # train_network:
  #   cmd: python train_network.py
  #   deps:
  #     - noisy_data/
  #   outs:
  #     - model/
  #   metrics_no_cache:
  #     - metrics/training_metrics.json

  # test_network:
  #   cmd: python test_network.py
  #   deps:
  #     - model/
  #     - noisy_data/
  #   outs:
  #     - test_results/
  #   metrics_no_cache:
  #     - metrics/test_metrics.json
