
generate_data:
  batch_size: 1

geometry:
  N: [256, 256, 128]
  pml_margin: 20
  dx: [0.1e-3, 0.1e-3, 0.1e-3]
  c: 1500
  cfl: 0.3

simulate:
  num_sensors: 64
  sensor_margin: 10 # added to the pml_margin


reconstruct:
  noise_amplitude: amplitude

