
generate_data:
  batch_size: 1

geometry:
  N: [128, 128, 128]
  dx: [0.1e-3, 0.1e-3, 0.1e-3]
  c: 1500
  cfl: 0.3
  pml_margin: 20 # each side
  tissue_margin: [5, 5, 5] # Added to pml_margin on each side
  sensor_margin: [5, 5, 5] # Added to pml_margin on each side; sensor_margin[2] < tissue_margin[2] 
  num_sensors: 81

# simulate:


reconstruct:
  noise_amplitude: 0.05

