[project]
name = "pact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bezier>=2024.6.20",
    "dm-pix>=0.4.4",
    "flax>=0.10.4",
    "itk>=5.4.3",
    "jax[cuda]>=0.4.38",
    "jwave>=0.2.1",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "optax>=0.2.4",
    "perlin-numpy>=0.0.1",
    "scikit-image>=0.25.2",
    "v-system",
]

[tool.uv.sources]
v-system = { path = "V-System" }
